name: PluginChannelLogger
main: me.craftgpt.channellogger.PluginChannelLogger
version: 1.2
api-version: 1.13
depend: [ProtocolLib]
commands:
  pcl:
    usage: /pcl <start|stop|logto>
    description: Control plugin channel logger and logging output